version: "3.0"

expectations:
  population_size: 1000

actions:
 
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_prim_cov:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prim_cov
    outputs:
      highly_sensitive:
        cohort: output/input_prim_cov.csv

  generate_results:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/generate_results.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_study_population, generate_study_population_prim_cov]
    outputs:
      moderately_sensitive:
        notebook: output/generate_results.html
        tables: output/summary_tabl*.csv
        id_tables: output/identification_table_*.csv
        cm: output/cm_*.jpeg
  
