version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_study_population_ae:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ae
    outputs:
      highly_sensitive:
        cohort: output/input_ae.csv

  generate_ae_count:
    run: python:latest python analysis/ae_count.py
    needs: [generate_study_population_ae]
    outputs:
      moderately_sensitive:
        count: output/ae_count.json
        hospital_count: output/hospital_admission_count.json
        emergency_hospital_count: output/emergency_hospital_admission_count.json
        time_diff: output/time_diff_count.json
        same_count: output/same_count.json

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  